#!/usr/bin/node

//Returns the paragraphs from a wikipedia link, stripped of reference numbers.

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
  //simulate a Document Object Model.
  let { document } = (new JSDOM(body)).window;

  //Grab all the paragraphs and references.
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");
}


console.log(url);
